Change phase duration to maximum phase duration
BlockScience/aztec-gddt pull request #109
Opened 2024-02-20 12:40 UTC by eightarmsninebrains

In the previous version, there was a single parameter `phase_duration_name` for each name. The model assumed that all such parameters were fixed values.  

This change:
- creates  parameters `phase_duration_name_min_blocks` and `phase_duration_name_max_blocks` for each name. 
- uses "phase_duration_name_max_blocks" to determine if the phase duration has been exceeded. 

The next steps are:
- use `phase_duration_name_min_blocks` in the logic. (Make sure that the logic has the intended effect.)
- create methods that make it easier to construct parameters with specific values, for parameter sweeps and experiments.

2024-02-25 22:33 UTC, eightarmsninebrains commented
Further updates to create time series signals for shock scenarios, and make them compatible with the current `GasEstimator` architecture.

2024-02-28 16:25 UTC, danlessa requested changes

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/logic.py
> +                SAFETY_BUFFER = 2 * fee # HACK:
make that a parameter

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/logic.py
> +                        advance_blocks = remaining_time #TODO: double-check this.
intent: we'll move the L2 time forward by `advance_blocks`

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/logic.py
> +                expected_costs = params['op_costs'] + fee + SAFETY_BUFFER
parametrize

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/logic.py
>                  expected_rewards = state['cumm_block_rewards'] - history[-1][0]['cumm_block_rewards']
add XXX in here: expected rewards = reward on last timestep

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/params.py
> +SINGLE_SHOCK_GAS_ESTIMATORS = L1GasEstimators(
note: the above estimators are relevant for the Gas Fee, not for the Gas Units per Tx

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/params.py
> +def intermit_shock_l1_gas_estimate(state: AztecModelState):
note: the above estimators are relevant for the Gas Fee, not for the Gas Units per Tx

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/params.py
> +                                     phase_duration_proposal_min_blocks=0, # TODO
update numbers to reflect the workplan https://hackmd.io/@blockscience/B1ZQ_TX3T

2024-02-28 16:25 UTC, danlessa commented on aztec_gddt/types.py
> +    logic: Dict[str, Callable[Dict, Any]] = None #placeholder for general system logic
what is general system logic?

2024-02-28 18:08 UTC, merged